version: '3.7'

services:

  frontend:
    container_name: front
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/front'
      - '/front/node_modules'
    ports:
      - '4200:4200'